services_2_to_1:
  -
    service: /on
    type: std_srvs/SetBool
  -
    service: /off
    type: std_srvs/SetBool
  -
    service: /grip_status
    type: std_srvs/SetBool
  -
    service: /get_item_pose  # ROS1 service name
    type: vision_engine/Locations  # The ROS2 type name
  -
    service: /do_inferences  # ROS1 service name
    type: std_srvs/SetBool  # The ROS2 type name